name: Unapy CI

on:
  push:
    branches:
      - master
    paths:
      - 'packages/unapy/**'

jobs:

  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: guilhermebkel/unapy:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Run on production
      uses: floms/action-caprover@v1
      with:
        host: '${{ secrets.CAPROVER_HOST }}'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        app: 'uno-game-api'
        image: 'guilhermebkel/unapy:latest'
